package:
  name: toytree
  version: '0.2.1'

source:
  url: https://github.com/eaton-lab/toytree/archive/0.2.1.tar.gz
  sha256: 199963f41537b539f8efa017d7682e9f9dc153e7d619e6ba7e7133f643bbab76

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python
  
requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.10
    - toyplot >=0.17.0 
    - requests
    - future
    # - notebook
    # - nbconvert

test:
  imports:
    - toytree

about:
  home: http://github.com/eaton-lab/toytree
  license: GPLv3
  summary: Minimalist tree plotting library using Toyplot.
