package:
  name: toytree
  version: {{ GIT_DESCRIBE_NUMBER }}  ## e.g., 0.1.6-9
  #version: {{ environ.get('GIT_DESCRIBE_NUMBER', '') }}  

source:
  git_url: https://github.com/eaton-lab/toytree.git
  git_tag: {{ GIT_DESCRIBE_TAG }}    ## checks out this tag
  #git_tag: {{ environ.get('GIT_DESCRIBE_TAG', '') }}  ## e.g., 0.1.6-9-g1e6879
  #git_tag: 0.1.5
  ## git_tag: {{ environ.get('GIT_DESCRIBE_TAG', '') }}  

build:
  ##string: 'beta'  ## {{ environ.get('GIT_DESCRIBE_HASH', '') }}
  #number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - toyplot >=0.16.1  ## eaton-lab forked version for now
    - pypng
    - reportlab
    - nbconvert
    - jupyter
    - requests
  run:
    - python
    - setuptools
    - numpy >=1.7
    - toyplot >=0.16.1  ## eaton-lab forked version for now
    - pypng
    - reportlab
    - jupyter
    - nbconvert
    - requests

test:
  imports:
    - toytree

about:
  home: http://github.com/eaton-lab/toytree
  license: GPLv3
  summary: Minimalist tree plotting library using Toyplot.
