package:
  name: toytree
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/eaton-lab/toytree.git

build:
  script: python setup.py install
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - pypng
    - reportlab
    - colormath
    - numpy >=1.7
    - toyplot >=v0.13.0
  run:
    - numpy >=1.7
    - toyplot >=v0.13.0

about:
  home: http://github.com/eaton-lab/toytree
  license: GPLv3
  summary: Minimalist tree plotting library using toyplot graphs
