
## tag grabs latest commit tag on the git_tag branch/tag
package:
  name: toytree
  version: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  #version: {{ GIT_DESCRIBE_TAG }}        ## 'toytree-0.1.5-py27_0.tar.bz2

source:
  git_url: https://github.com/eaton-lab/toytree.git
  git_tag: pystyling

## increments build of the same number
build:
  #number: {{ GIT_DESCRIBE_NUMBER }}
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - toyplot >=0.16.1  ## eaton-lab forked version for now
    - pypng
    - reportlab
    - jupyter
    - nbconvert
    - requests
  run:
    - python
    - setuptools
    - numpy >=1.7
    - toyplot >=0.16.1  ## eaton-lab forked version for now
    - pypng
    - reportlab
    - jupyter
    - nbconvert
    - requests

test:
  imports:
    - toytree

about:
  home: http://github.com/eaton-lab/toytree
  license: GPLv3
  summary: Minimalist tree plotting library using Toyplot.
