package:
  name: toytree
  version: '1.1.2'

source:
  url: https://github.com/eaton-lab/toytree/archive/1.1.2.tar.gz
  sha256: f63059dc6c3d70c545497b0ca914fe01ec72ea0580baa80ba44ef5c6c01fca2a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python
  
requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.10
    - toyplot >=0.17.0 
    - requests
    - future
    # - notebook
    # - nbconvert

test:
  imports:
    - toytree

about:
  home: http://github.com/eaton-lab/toytree
  license: GPLv3
  summary: Minimalist tree plotting library using Toyplot.
