package:
  name: toytree
  version: '1.0.0'

source:
  url: https://github.com/eaton-lab/toytree/archive/1.0.0.tar.gz
  sha256: 7f19a50a21136dba9a0dd5e223ac5829f1997e14b3cfb82097983002820833eb

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python
  
requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.10
    - toyplot >=0.17.0 
    - requests
    - future
    # - notebook
    # - nbconvert

test:
  imports:
    - toytree

about:
  home: http://github.com/eaton-lab/toytree
  license: GPLv3
  summary: Minimalist tree plotting library using Toyplot.
