package:
  name: toytree
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}  ## current tag on master

source:
  git_url: https://github.com/eaton-lab/toytree.git
  git_tag: 0.1.4
  ## git_tag: {{ environ.get('GIT_DESCRIBE_TAG', '') }}  ## current tag on master

build:
  ##string: 'beta'  ## {{ environ.get('GIT_DESCRIBE_HASH', '') }}
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - toyplot >=0.16.0
    - pypng
    - reportlab
    - nbconvert
    - jupyter
  run:
    - python
    - setuptools
    - numpy >=1.7
    - toyplot >=0.16.0
    - pypng
    - reportlab
    - jupyter
    - nbconvert

test:
  imports:
    - toytree

about:
  home: http://github.com/eaton-lab/toytree
  license: GPLv3
  summary: Minimalist tree plotting library using Toyplot.
