package:
  name: custom_inherit
  version: '2.2.0'

source:
  url: https://github.com/meowklaski/custom_inherit/archive/2.2.0.tar.gz
  sha256: e668b663cd8734778b465d2f2995d1b768e0af7dc1f957110ca212ac9d47db9a

build:
  number: 1
  script: python setup.py install 
  noarch: python

requirements:
  host:
    - python
  run:
    - python

test:
  imports:
    - custom_inherit

about:
  home: https://github.com/meowklaski/custom_inherit.git
  license: MIT
  summary: Light-weight tools for inheriting docstrings in customizeable ways.

