package:
  name: custom_inherit
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/meowklaski/custom_inherit.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: python setup.py install 

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python {{ python }}
    - setuptools

test:
  imports:
    - custom_inherit

about:
  home: https://github.com/meowklaski/custom_inherit.git
  license: MIT
  summary: Light-weight tools for inheriting docstrings in customizeable ways.

