package:
  name: toyplot
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }} 

source:
  git_url: https://github.com/eaton-lab/toyplot.git
  git_rev: 0.14.4

build:
  script: build.sh 
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python 
    - setuptools
    - colormath >=2.1.0
    - multipledispatch
    - numpy >=1.8.2
    - pypng >=0.0.18
    - pillow
    - reportlab
    - pip
    - graphviz
    - mock
    - networkx
    - pandas >=0.14.1
  run:
    - python 
    - setuptools
    - colormath >=2.1.0
    - multipledispatch
    - numpy >=1.8.2
    - pypng >=0.0.18
    - pillow
    - reportlab
    - pip
    - graphviz
    - mock
    - networkx
    - pandas >=0.14.1

    
about:
  home: http://github.com/sandialabs/toyplot
  license: BSD
  summary: A modern plotting toolkit supporting electronic publishing and reproducibility.

