package:
  name: toyplot
  version: "0.18.0"

source:
  url: https://github.com/sandialabs/toyplot/archive/v0.18.0.tar.gz
  sha256: e4c2b64a72d9d7059db844633f46b489b07f84e9f0f24df77bbcc82c04711f1c

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.8.2
    - custom_inherit     # eaton-lab
    - multipledispatch   # conda
    - pypng <=0.0.20     # eaton-lab
    - reportlab          # conda
    - six                # 
    - pillow             # pdf; optional
    - ghostscript        # eaton-lab or conda-forge / optional

test:
  imports:
    - toyplot
   
about:
  home: http://github.com/sandialabs/toyplot
  license: BSD
  summary: A modern plotting toolkit supporting electronic publishing and reproducibility.

